# Generated by Django 6.0.1 on 2026-01-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactleads",
            options={
                "verbose_name": "Contact Lead",
                "verbose_name_plural": "Contact Leads",
            },
        ),
    ]
