# Generated by Django 6.0.1 on 2026-01-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=300)),
                ("skill_image", models.ImageField(upload_to="skills/")),
                (
                    "skill_category",
                    models.CharField(
                        choices=[
                            ("Programming Languages", "Programming Languages"),
                            ("Frontend Technologies", "Frontend Technologies"),
                            ("Backend Frameworks", "Backend Frameworks"),
                            ("Databases", "Databases"),
                            ("Tools & Platforms", "Tools & Platforms"),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
    ]
