# Generated by Django 6.0.1 on 2026-01-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="skill_category",
            field=models.CharField(
                choices=[
                    ("Programming Languages", "Programming Languages"),
                    ("Frontend Technologies", "Frontend Technologies"),
                    ("Backend Frameworks", "Backend Frameworks"),
                    ("Databases", "Databases"),
                    ("Data Science Technologies", "Data Science Technologies"),
                    ("Tools & Platforms", "Tools & Platforms"),
                ],
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="skills",
            name="skill_image",
            field=models.ImageField(blank=True, null=True, upload_to="skills/"),
        ),
    ]
