# Generated by Django 6.0.1 on 2026-01-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"verbose_name": "Degree", "verbose_name_plural": "Degrees"},
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
