# Generated by Django 6.0.1 on 2026-01-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("focus_areas", models.CharField(max_length=300)),
            ],
        ),
    ]
