# Generated by Django 6.0.1 on 2026-01-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bio",
            options={"verbose_name": "Bio", "verbose_name_plural": "Bio"},
        ),
    ]
